# Generated by Django 4.1.3 on 2022-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=200)),
                ('Año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especie', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=200)),
                ('Edad', models.IntegerField()),
            ],
        ),
    ]
