# Generated by Django 4.1.3 on 2022-12-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares_app', '0002_automovil_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automovil',
            old_name='Año',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='automovil',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='automovil',
            old_name='Modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='Especie',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
